### ISSUE TITLE
Missing steps at screenshot 

### ISSUE THREAD

**Issue by kienpham2000** [awslabs/aws-amplify-unicorntrivia-workshop#8] opened 2019-08-15 18:38 UTC
At this page https://github.com/awslabs/aws-amplify-unicorntrivia-workshop/blob/master/documentation/admin_panel_doc.md on Step 5, it's missing the last step in the screenshot. 

```? Do you want to generate code for your newly created GraphQL API Yes
? Choose the code generation language target javascript
? Enter the file name pattern of graphql queries, mutations and subscriptions
 src/graphql/**/*.js
? Do you want to generate/update all possible GraphQL operations - queries, m
utations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deep
```

**Comment by wizage** [comment] 2019-08-16 17:03
@axptwig can you update this screenshot to reflect the new changes to the CLI.

**Comment by wizage** [comment] 2019-08-16 17:05
Closing as duplicate of #6

**Closed by wizage** 2019-08-16 17:05 UTC
